### ISSUE TITLE
Organize examples by technology/use case, rather than analysis type

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-examples#102] opened 2020-06-29 15:12 UTC
Related to #101 and #92 

If we present things as a follow along tutorial, it makes sense to me to organize material by technology or use case rather than analysis type. Specifically, duplicating analysis _types_ like gene identifier conversion across separate microarray and RNA-seq "tracks" allows for some repetition of concepts and more opportunities to vary things in a way that supports learning (e.g., use different species [#98]). 

Here are some initial thoughts about how to organize things, where the listing of individual types of analyses are incomplete and for illustrative purposes:

* Introduction
  * Setting up RStudio
  * Obtaining files locally, etc.
  * Skip to "advanced use cases" (more on that below)
* Microarray 
  * Background on how we process microarray data (similar information to what's in the docs)
  * Clustering
  * Gene ID conversion
  * Differential gene expression analysis
  * Pathway analysis
* RNA-seq
  * Background on how we process RNA-seq data (similar information to what's in the docs)
  * Clustering
  * Gene ID conversion
  * Differential gene expression analysis
  * Pathway analysis
* Larger cross-experiment, cross-platform experiments & compendium
  * How we process these datasets in general and in the specific compendium case (similar information to what's in the docs)
  * Machine learning examples
* "Advanced usage"
  * Normalizing your own data
  * API usage examples
  * Eventually: Python Client
  * Eventually: Command line
  * Eventually: R Client

Where for the clients this may be more like a place where we link out to other documentation specific to those clients, but include some info about installation, for example.

**Comment by cansavvy** [comment] 2020-07-15 15:14
The heart of this issue has been addressed in #120

**Comment by cansavvy** [comment] 2020-07-15 15:19
Although the heart of the issue is addressed, we should keep this open for reference as well as the "Advanced topics" section part of this outline which is not yet added.

**Closed** 2021-01-13 19:19 UTC
Labels: future thoughts
